### ISSUE TITLE
[BUG] Android 11 crash - Unable to get provider tech.linjiang.pandora.Pandora

### ISSUE THREAD

**Issue by Phoenix986** [rafaco/InAppDevTools#14]
I followed all the basic steps to setup the library, but on android 11 devices I get this error.
With android 9 all works perfectly

![image](https://user-images.githubusercontent.com/3393295/104585666-a6cb6d00-5664-11eb-8ea2-d9f421543421.png)

**Comment by rafaco** [comment]
Hi @Phoenix986, thanks a lot for using Iadt and for reporting the first external issue to this project :1st_place_medal::+1:

Unfortunately I can not reproduce this crash following the basic steps over a standard app project from template on an Android 11 device. But this exception is well known for me and I've been working on a similar crash happening for React Native apps. This changes are not published already but it will be done this weekend under a brand new version (0.0.58). If you don't mind, wait to test your issue against the next version.

If 0.0.58 don't fix your issue, it would be very helpful for me to have the full log of the Iadt startup. To do so, please add 'debug=true' and 'injectEventsOnLogcat=true' to the inappdevtools gradle configuration closure, rebuild your app into your Android 11 device and send me the logcat output. Also let me know if your app is using more than one Android process or if your app is doing any activity redirection on startup.

Cheers!

**Comment by rafaco** [comment]
Hi, I've just published [Iadt v0.0.58](https://github.com/rafaco/InAppDevTools/releases/tag/v0.0.58), please test if it fix your issue and let me know.

A couple of considerations:
- As part of the startup process changes, we are now detecting crashes on Pandora initialisation (like the one from this issue) and auto disabling related features when it happens. If you can now reach our overlay interface without a crash, please also check that any of them are enabled. To do so just check if you can navigate to network, view or storage inspectors from our home screen.
- This release introduce some new error logs on startup but they don't cause a crash. I will fix it with a small release in few days.

**Comment by Phoenix986** [comment]
hi @rafaco, thanks for the update, i will try it asap, and i will let you know if the problem is gone and if all Pandora's features work

**Comment by rafaco** [comment]
This issue was fixed a year ago
